# Alembic Configuration File

[alembic]
# path to migration scripts
script_location = migrations

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
#file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date
# within the migration file as well as the filename.
# string value is passed to be used by the `datetime.datetime.fromtimestamp()` function
# leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field that's appended to a revision file
# when askforedits is True. The default value is 40
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory. By default, source files are
# required, so untracked .pyc/.pyo files won't be
# included.
# sourceless = false

# When set to "true", this option enforces UTC timestamps
# on revision metadata, regardless of the timestamp_output_config setting.
# Of course, this must be the first alembic version where this setting is used
# so legacy timestamp formats will only be used with older versions.
# If this value is false, new timestamps are output in whatever format specified by
# timestamp_output_config.
# utc_now = false

# Logging configuration
[loggers]
keys = root,sqlalchemy.engine

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy.engine]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
